name: Build

on:
  push:

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta7"

      - name: Run build
        run: tools/Debug.bat
